parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2021
  sourceType: module
  ecmaFeatures:
    jsx: true

plugins:
  - prettier
  - react
  - react-hooks
  - import
  - "@typescript-eslint/eslint-plugin"

settings:
  react:
    version: "detect"

rules:
  prettier/prettier: 2

  no-undef: 2
  # no-unused-vars: 2
  "@typescript-eslint/no-unused-vars": [2, { "ignoreRestSiblings": true }]
  react/button-has-type: 2
  react/destructuring-assignment: 2
  react/forbid-dom-props: 2
  react/forbid-elements: 2
  react/forbid-foreign-prop-types: 2
  react/forbid-prop-types: 2
  react/no-access-state-in-setstate: 2
  react/no-danger: 2
  react/no-danger-with-children: 2
  react/no-deprecated: 2
  react/no-did-mount-set-state: 2
  react/no-did-update-set-state: 2
  react/no-direct-mutation-state: 2
  react/no-find-dom-node: 2
  react/no-is-mounted: 2
  react/no-set-state: 2
  react/no-string-refs: 2
  react/no-this-in-sfc: 2
  react/no-unescaped-entities: 2
  react/no-unknown-property: 2
  react/no-unsafe: 2
  react/no-unused-state: 2
  react/no-will-update-set-state: 2
  react/prefer-es6-class: 2
  react/prefer-read-only-props: 2
  react/prefer-stateless-function: 2
  react/require-optimization: 2
  react/require-render-return: 2
  react/self-closing-comp: 2
  react/sort-comp: 2
  react/state-in-constructor: 2
  react/static-property-placement: 2
  react/style-prop-object: 2
  react/void-dom-elements-no-children: 2
  react/jsx-boolean-value: 2
  react/jsx-fragments: 2
  react/jsx-handler-names: 2
  react/jsx-key: 2
  react/jsx-no-bind: 2
  react/jsx-no-constructed-context-values: 2
  react/jsx-no-duplicate-props: 2
  react/jsx-no-script-url: 2
  react/jsx-no-target-blank: 2
  react/jsx-no-undef: 2
  react/jsx-no-useless-fragment: 2
  react/jsx-pascal-case: 2
  react/jsx-uses-react: 2
  react/jsx-uses-vars: 2

  react-hooks/rules-of-hooks: 2
  react-hooks/exhaustive-deps: 2

  import/order: [2, { newlines-between: "always" }]
